### PR TITLE
Fix n() error and update DESCRIPTION and NEWS

### PR DESCRIPTION
**Pull request by koheiw**
Address #12

### CODE REVIEW

**Comment by koheiw** [comment]
Travis is failing because there is no API key set in environment variables.

**Comment by maelle** [comment]
Thanks a ton!

Do you need this to get to CRAN soon?

**Comment by koheiw** [comment]
Thanks for merging. It is good to update the CRAN version, but not urgent. I was thinking to use this package in my teaching at university. Geoparser has a potential, so I am happy to contribute to the package more substantively.

**Comment by maelle** [comment]
@koheiw I'll try to do the CRAN release soon. If you have any idea for improving the package, feel free to open issues and then PRs! :smile_cat:

**Pull request merged**
